version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: articles-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles_db
    ports:
      - "5432:5432"
    volumes:
      - tmp_pg_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: articles
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/articles_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8081:8081"

volumes:
  tmp_pg_data:
    driver: local
